# Hugo-Geekdoc Theme Config

baseURL = "https://fantastic-fiesta-da4ab8e5.pages.github.io/"

theme = "hugo-geekdoc"

enableGitInfo = false

pluralizeListTitles = false
pygmentsUseClasses = true

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "paraiso-dark"
    tabWidth = 4

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[markup.goldmark.extensions]
    typographer = true

[markup.goldmark.renderer]
    unsafe = true

# Disable geekdoc default theme settings
[params]
geekdocRepo = ""
geekdocEditPath = ""
# disable non-working search when serving from local file system
geekdocSearch = false