# Build from cli: hugo --environment=local

# for static serving from local file system
baseURL = ""
relativeURLs = "true"

[params]
geekdocRepo = ""
geekdocEditPath = ""
# disable non-working search when serving from local file system
geekdocSearch = false