languageCode = "en-us"
title = "VehicleApp using Python - Release Documentation"

baseURL = "http://example.org/"

# Keep uglyURLs for now, as this provides the best out of the box support for rendering markdown images in VSCode preview and Hugo
# Link: https://gohugo.io/content-management/urls/#ugly-urls
uglyURLs = "true"

enableGitInfo = true

theme = "hugo-geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
    ordered= false
    startLevel= 1
    endLevel= 3


[params]
geekdocRepo = "https://github.com/SoftwareDefinedVehicle/vehicle-app-python-template"
geekdocEditPath = "edit/main/hugo/content"
geekdocCollapseSection = true