name: Install IoT Event Analytcs platform
description: Build IoT Event Analytics platform from GENIVI/iot-event-analytics and upload the platform images to GitHub Container Registry

runs:
  using: "composite"
  steps:
    - name: Build and upload images if not exist
      shell: bash
      env:
        MOSQUITTO_CONFIG_DIR: ${{github.workspace}}/config/mosquitto
        PLATFORM_CONFIG_DIR: ${{github.workspace}}/config/platform
        MQTT_PORT: 1883
        API_PORT: 8080
      run: |
          echo "Building IotEA platform images ..."

          git clone --single-branch --branch=develop --depth=1 'https://github.com/GENIVI/iot-event-analytics' 'build/iotea'

          cd ${{github.workspace}}/build/iotea/docker-compose

          docker-compose -f "docker-compose.mosquitto.yml" -f "docker-compose.platform.yml" build

          echo "Building IotEA platform images ... DONE"


