# /********************************************************************************
# * Copyright (c) 2021 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# ********************************************************************************/

SEAT ADJUSTER APP

kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app1"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: app1
        image: sdvacr.azurecr.io/app1:<version>
        imagePullPolicy: Always
        resources:
        ports: