# /********************************************************************************
# * Copyright (c) 2021 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# ********************************************************************************/

name: CI workflow

on:
  workflow_dispatch:
  push:
    # Run only on branches/commits and not tags
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Enable once the ACTIONS_REPOSITORY_TOKEN org secret is set
      # - name: Clone actions repository
      #   uses: actions/checkout@v2
      #   run: git clone https://github.com/SoftwareDefinedVehicle/swdc-actions.git 
      #   with:
      #     repository: SoftwareDefinedVehicle/swdc-actions
      #     token: ${{ secrets.ACTIONS_REPOSITORY_TOKEN }}
      #     path: "./.github/swdc-actions"

      - name: Install Dapr
        uses: dapr/setup-dapr@v1
        with:
          version: "1.4.0"

      - name: Initialize Dapr
        shell: pwsh
        run: |
          Write-Output "::group::dapr init"
          dapr init
          Write-Output "::endgroup::"
          dapr --version

      - name: Initialize vehicleApp projects
        shell: pwsh
        run: |
          Write-Output "::group::Initialize vehicleApp"
          Import-Module ./.sdv/Sdv.psm1 -Force
          Find-SdvVehicleApp | Get-SdvComponent | Initialize-SdvComponent -Verbose
          Write-Output "::endgroup::"

      - name: Start mqtt
        shell: bash
        run: docker run -d -p 1883:1883 -p 9001:9001 eclipse-mosquitto:1.6.9

      - name: unit test
        shell: bash
        run: |
          pip install pytest
          pytest --rootdir . --override-ini junit_family=xunit1 --junit-xml=./.sdv/tmp/UnitTest/junit.xml ./src

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./.sdv/tmp/UnitTest/junit.xml

      - name: Package unit test files
        uses: ./.github/swdc-actions/documentation/package
        with:
          name: "UnitTest"
          type: "UnitTest"
          schema: "JUnit"
          sourcePath: ./.sdv/tmp/UnitTest/junit.xml
          packagePath: ./.sdv/tmp/Documentation/renderer

      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: 'test-results'
          path: |
            .sdv/tmp/Documentation/renderer/*

  build-images:
      runs-on: ubuntu-latest
      name: Building images

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2      

      - name: Check Docker version
        run: docker --version    

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: github-repository-name-case-adjusted
        name: Prepare repository name in lower case for docker upload. This supports repository names in mixed case
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      # Enable once the build time is acceptable    
      # - name: Build multi-arch image
      #   id: image_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     pull: true
      #     push: false
      #     outputs: |
      #       type=oci,dest=./vapp-container-image.tar
      #     context: .
      #     file: src/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     labels: |
      #       org.opencontainers.image.source=https://github.com/${{steps.github-repository-name-case-adjusted.outputs.lowercase}}
               
      - name: Building images
        shell: pwsh
        env:
          VAPP_VERSION: ${{ github.sha }}
          GIT_HUB_REPOSITORY_NAME_LOWER_CASE: ${{ steps.github-repository-name-case-adjusted.outputs.lowercase }}
        run: |
          Import-Module ./.sdv/Sdv.psm1 -force
          foreach($Component in (Find-SdvVehicleApp | Get-SdvComponent)) {
            Enter-LoggingGroup ("Building image for component '{0}'" -f $Component.Name)
          
            $ImageName = $Component.Name
            $DockerFile = Join-Path $Component.Folder -ChildPath "Dockerfile"
            $DockerFolder = $Component.DockerFolder
            Write-Output ("Building image '{0}' from folder '{1}' with docker file '{2}'" -f $ImageName, $DockerFolder, $DockerFile)
            docker build -t $ImageName -f $DockerFile $DockerFolder

            Write-Output "Listing all local images"
            docker image list
            Exit-LoggingGroup
            docker image list $ImageName
          }

      - name: Uploading images
        shell: pwsh
        env:
          VAPP_VERSION: ${{ github.sha }}
          GIT_HUB_REPOSITORY_NAME_LOWER_CASE: ${{ steps.github-repository-name-case-adjusted.outputs.lowercase }}
        run: |
          Import-Module ./.sdv/Sdv.psm1 -force
          foreach($Component in (Find-SdvVehicleApp | Get-SdvComponent)) {
            Enter-LoggingGroup ("Uploading image of component '{0}'" -f $Component.Name)
            $ImageName = $Component.Name

            Write-Output "Listing local images"
            docker image list

            Write-Output ("Getting id of '{0}'" -f $ImageName)
            $ID = docker images $ImageName -q
            Write-Output ("Selected id '{0}'" -f $ID)

            $GHCRPath = "ghcr.io/$env:GIT_HUB_REPOSITORY_NAME_LOWER_CASE/${ImageName}:$env:VAPP_VERSION"
            Write-Output ("Tagging '{0}' with '{1}'" -f $ID, $GHCRPath)
            docker tag $ID $GHCRPath 

            Write-Output ("Pushing '{0}'" -f $GHCRPath)
            docker push $GHCRPath 
            Exit-LoggingGroup
          }

  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    needs: [build-images, unit-tests]

    steps:
      - name: Test SeatAdjuster vehicleApp 
        shell: pwsh
        run: .sdv/Test-SdvVehicleApp.ps1     