# /********************************************************************************
# * Copyright (c) 2021 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Eclipse Public License 2.0 which is available at
# * http://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# ********************************************************************************/

name: CI workflow

on:
  workflow_dispatch:
  push:
    # Run only on branches/commits and not tags
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Docker version
        run: docker --version

      - name: Install Dapr
        uses: dapr/setup-dapr@v1
        with:
          version: "1.4.0"

      - name: Initialize Dapr
        shell: pwsh
        run: |
          Write-Output "::group::dapr init"
          dapr init
          Write-Output "::endgroup::"
          dapr --version

      - name: Initialize vehicleApp projects
        shell: pwsh
        run: |
          Write-Output "::group::Initialize vehicleApp"
          Import-Module ./.sdv/Sdv.psm1 -Force
          $VerbosePreference="continue"
          Find-SdvVehicleApp | Get-SdvComponent | Initialize-SdvComponent
          Write-Output "::endgroup::"

      - name: Start mqtt
        shell: bash
        run: docker run -d -p 1883:1883 -p 9001:9001 eclipse-mosquitto:1.6.9

      - name: Test SeatAdjuster vehicleApp 
        shell: pwsh
        run: .sdv/Test-SdvVehicleApp.ps1 SeatAdjuster -InPipeline